"""Guards for cached thumbnails and downloads going stale.

Both caches in this app key on a path alone: ``Thumbnailer.thumb_path_for``
hashes the local file path, and the Nextcloud client derives its cache names
from the DAV path. A photo edited in place — a rotation baked in by the viewer,
an EXIF write after a capture, an external editor, a file replaced on the
server — therefore keeps its cache filename, and a bare "does the cache file
exist?" test would serve the pre-edit image for as long as the photo keeps its
name.

The rule both caches now follow is the same: a cached file is stamped with its
*source's* modification time, so the two timestamps match while the cache entry
is current and the source's runs ahead the moment it is rewritten.

The comparison is deliberately one-directional (``>=``): entries written before
stamping existed carry their generation time, which is later than the source's,
so upgrading must not invalidate a whole library at once. The scanner covers the
other direction, because it compares against the mtime recorded in the index.
"""

from __future__ import annotations

import os
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

import muga.thumbnails as thumbnails
from muga.thumbnails import Thumbnailer

PILImage = pytest.importorskip("PIL.Image")
nc = pytest.importorskip("muga.nextcloud")


LANDSCAPE = (40, 20)
PORTRAIT = (20, 40)


def _make_image(path: Path, size: tuple[int, int], color: tuple[int, int, int]) -> None:
    PILImage.new("RGB", size, color).save(str(path), "JPEG", quality=90)


def _touch(path: Path, mtime: float) -> None:
    """Set *path*'s mtime, leaving atime alone."""
    os.utime(path, (path.stat().st_atime, mtime))


def _shift_mtime(path: Path, seconds: float) -> None:
    """Move *path*'s mtime by *seconds*.

    Tests that depend on one file being newer than another say so explicitly
    rather than relying on two writes landing in different filesystem timestamp
    ticks — FAT on an SD card rounds to two seconds, and Muga runs on phones.
    """
    _touch(path, path.stat().st_mtime + seconds)


@pytest.fixture()
def thumbnailer(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Thumbnailer:
    monkeypatch.setattr(thumbnails, "THUMB_DIR", tmp_path / "thumbs")
    return Thumbnailer()


@pytest.fixture()
def photo(tmp_path: Path) -> Path:
    source = tmp_path / "photo.jpg"
    _make_image(source, LANDSCAPE, (200, 30, 30))
    return source


# ---------------------------------------------------------------------------
# Local thumbnails
# ---------------------------------------------------------------------------

def test_an_edited_photo_gets_a_new_thumbnail(thumbnailer: Thumbnailer, photo: Path) -> None:
    """The case the user hits: rotate or edit a photo, and the grid tile has to
    turn with it instead of showing the old orientation."""
    first = thumbnailer.ensure_thumbnail(photo, "image")
    assert first is not None
    assert PILImage.open(first).size[0] > PILImage.open(first).size[1]

    _make_image(photo, PORTRAIT, (30, 30, 200))
    _shift_mtime(photo, 10.0)

    second = thumbnailer.ensure_thumbnail(photo, "image")
    assert second == first, "the thumbnail keeps its deterministic path"
    regenerated = PILImage.open(second)
    assert regenerated.size[1] > regenerated.size[0], "still showing the pre-edit image"


def test_an_unchanged_photo_reuses_its_thumbnail(
    thumbnailer: Thumbnailer, photo: Path,
) -> None:
    """The freshness check must not turn every scan into a full re-decode of the
    library — that is the whole point of the cache."""
    thumbnailer.ensure_thumbnail(photo, "image")

    with patch.object(
        Thumbnailer, "_image_thumbnail", autospec=True,
    ) as decode:
        assert thumbnailer.ensure_thumbnail(photo, "image") is not None
    decode.assert_not_called()


def test_a_thumbnail_from_before_stamping_is_kept(
    thumbnailer: Thumbnailer, photo: Path,
) -> None:
    """Thumbnails generated by an older Muga carry their generation time, which
    is later than the source's. Treating those as stale would re-decode every
    photo on the first launch after an upgrade."""
    target = thumbnailer.thumb_path_for(photo)
    thumbnailer.ensure_thumbnail(photo, "image")
    _touch(target, photo.stat().st_mtime + 500)

    with patch.object(Thumbnailer, "_image_thumbnail", autospec=True) as decode:
        thumbnailer.ensure_thumbnail(photo, "image")
    decode.assert_not_called()


def test_an_unreadable_source_keeps_its_cached_thumbnail(
    thumbnailer: Thumbnailer, photo: Path,
) -> None:
    """An unmounted drive or a permission change leaves nothing to regenerate
    from, so the cached thumbnail is the best answer available — a stale tile
    beats a blank one."""
    first = thumbnailer.ensure_thumbnail(photo, "image")
    photo.unlink()

    assert thumbnailer.ensure_thumbnail(photo, "image") == first


def test_stamping_leaves_atime_alone(thumbnailer: Thumbnailer, photo: Path) -> None:
    """The disk-cache evictor sorts by atime (LRU). Stamping the mtime must not
    disturb that ordering, or eviction would start dropping the wrong files."""
    target = thumbnailer.thumb_path_for(photo)
    thumbnailer.ensure_thumbnail(photo, "image")

    stat = target.stat()
    assert stat.st_mtime == pytest.approx(photo.stat().st_mtime, abs=1e-3)
    # A file written moments ago has its atime at (or after) its creation, not
    # dragged back to the source's timestamp.
    assert stat.st_atime > photo.stat().st_mtime - 1


def test_a_video_thumbnail_is_stamped_too(
    thumbnailer: Thumbnailer, tmp_path: Path,
) -> None:
    """The video branch goes through an external thumbnailer rather than
    Pillow, so it needs the same stamp — otherwise a re-encoded clip keeps its
    old frame. Driven through a stub so the test needs no ffmpeg."""
    clip = tmp_path / "clip.mp4"
    clip.write_bytes(b"not really a video")
    target = thumbnailer.thumb_path_for(clip)

    def _fake_video(self, path: Path, dest: Path) -> str:
        _make_image(dest, LANDSCAPE, (10, 10, 10))
        return str(dest)

    with patch.object(Thumbnailer, "_video_thumbnail", autospec=True, side_effect=_fake_video):
        assert thumbnailer.ensure_thumbnail(clip, "video") == str(target)

    assert target.stat().st_mtime == pytest.approx(clip.stat().st_mtime, abs=1e-3)


def test_invalidate_forces_a_regeneration(thumbnailer: Thumbnailer, photo: Path) -> None:
    """The exact guarantee, for callers that cannot depend on timestamps — two
    rotations saved inside a single filesystem timestamp tick, say."""
    thumbnailer.ensure_thumbnail(photo, "image")
    target = thumbnailer.thumb_path_for(photo)
    assert target.exists()

    thumbnailer.invalidate(photo)

    assert not target.exists()
    with patch.object(Thumbnailer, "_image_thumbnail", autospec=True) as decode:
        thumbnailer.ensure_thumbnail(photo, "image")
    decode.assert_called_once()


def test_invalidate_is_quiet_about_a_thumbnail_that_is_not_there(
    thumbnailer: Thumbnailer, photo: Path,
) -> None:
    thumbnailer.invalidate(photo)  # must not raise


# ---------------------------------------------------------------------------
# Nextcloud caches
# ---------------------------------------------------------------------------

DAV = "/remote.php/dav/files/alice/Photos/holiday.jpg"


@pytest.fixture()
def nc_client(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setattr(nc, "_NC_THUMB", tmp_path / "nc-thumbs")
    monkeypatch.setattr(nc, "_NC_CACHE", tmp_path / "nc-cache")
    return nc.NextcloudClient("https://cloud.example.org", "alice", "app-password")


class _Response:
    """Stands in for http.client.HTTPResponse."""

    def __init__(self, body: bytes, status: int = 200) -> None:
        self.status = status
        self._body = body
        self._read = False

    def getheader(self, name, default=None):
        return {"Content-Length": str(len(self._body))}.get(name, default)

    def read(self, size=None):
        if self._read:
            return b""
        self._read = True
        return self._body


def _serving(client, body: bytes):
    """Patch *client*'s connections so any request answers with *body*."""
    conn = MagicMock()
    conn.getresponse.side_effect = lambda: _Response(body)
    return patch.multiple(
        client,
        _persistent_conn=MagicMock(return_value=conn),
        _conn=MagicMock(return_value=conn),
    )


def test_a_downloaded_thumbnail_carries_the_server_time(nc_client) -> None:
    """Stamping with the server's mtime rather than the download time is what
    makes the comparison immune to clock skew: a server running minutes ahead
    would otherwise make every entry look stale on every sweep."""
    with _serving(nc_client, b"thumb-bytes"):
        local = nc_client.ensure_thumbnail(DAV, remote_mtime=1_700_000_000.0)

    assert local is not None
    assert Path(local).stat().st_mtime == pytest.approx(1_700_000_000.0, abs=1e-3)


def test_a_file_replaced_on_the_server_is_fetched_again(nc_client) -> None:
    with _serving(nc_client, b"old-thumb"):
        first = nc_client.ensure_thumbnail(DAV, remote_mtime=1_700_000_000.0)
    assert Path(first).read_bytes() == b"old-thumb"

    with _serving(nc_client, b"new-thumb"):
        second = nc_client.ensure_thumbnail(DAV, remote_mtime=1_700_000_900.0)

    assert second == first
    assert Path(second).read_bytes() == b"new-thumb"


def test_an_unchanged_server_file_is_served_from_cache(nc_client) -> None:
    with _serving(nc_client, b"thumb") as _:
        nc_client.ensure_thumbnail(DAV, remote_mtime=1_700_000_000.0)

    conn = MagicMock()
    with patch.multiple(
        nc_client,
        _persistent_conn=MagicMock(return_value=conn),
        _conn=MagicMock(return_value=conn),
    ):
        assert nc_client.ensure_thumbnail(DAV, remote_mtime=1_700_000_000.0) is not None
    conn.request.assert_not_called()


@pytest.mark.parametrize("unknown", [None, 0.0])
def test_an_unknown_server_time_keeps_the_cached_copy(nc_client, unknown) -> None:
    """getlastmodified can be missing or unparseable (list_files falls back to
    0.0), and the lazy tile worker has no mtime at hand at all. Neither may turn
    into a re-download on every call."""
    with _serving(nc_client, b"thumb"):
        nc_client.ensure_thumbnail(DAV, remote_mtime=1_700_000_000.0)

    conn = MagicMock()
    with patch.multiple(
        nc_client,
        _persistent_conn=MagicMock(return_value=conn),
        _conn=MagicMock(return_value=conn),
    ):
        assert nc_client.ensure_thumbnail(DAV, remote_mtime=unknown) is not None
    conn.request.assert_not_called()


def test_a_cache_entry_from_before_stamping_is_kept(nc_client, tmp_path: Path) -> None:
    """Entries cached by an older Muga carry their download time, which is later
    than the server's mtime. Upgrading must not re-download the library."""
    with _serving(nc_client, b"thumb"):
        local = nc_client.ensure_thumbnail(DAV, remote_mtime=1_700_000_000.0)
    _touch(Path(local), 1_700_000_500.0)  # as if stamped by download time

    conn = MagicMock()
    with patch.multiple(
        nc_client,
        _persistent_conn=MagicMock(return_value=conn),
        _conn=MagicMock(return_value=conn),
    ):
        assert nc_client.ensure_thumbnail(DAV, remote_mtime=1_700_000_000.0) is not None
    conn.request.assert_not_called()


def test_a_replaced_original_is_downloaded_again(nc_client) -> None:
    """Same rule for the full-size cache the viewer reads from, not just the
    thumbnail."""
    with _serving(nc_client, b"old-original"):
        first = nc_client.download_file(DAV, remote_mtime=1_700_000_000.0)
    assert Path(first).read_bytes() == b"old-original"

    with _serving(nc_client, b"new-original"):
        second = nc_client.download_file(DAV, remote_mtime=1_700_000_900.0)

    assert second == first
    assert Path(second).read_bytes() == b"new-original"
